### ISSUE TITLE
Allowed?

### ISSUE THREAD

**Issue by elear** [scionassociation/scion-dp_I-D#11]
>  \*Note:\* The current SCION implementation uses the UDP/IP protocol as
   underlay.  However, the use of other underlay protocols is possible
   and allowed.

This last sentence makes it seem like one might never run SCION on its own.  Also, "allowed" isn't a word we should see in RFCs.

**Comment by nicorusti** [comment]
- [ ] check for instances of allowed (on all drafts) 
- [ ] clarify that SCION can may be run on its own L3

**Comment by knmeynell** [comment]
This is more complicated than at first sight at the remaining usage of 'allowed' relates to ISD voting rather directly to how the protocol is implemented. There are also numerous references to 'disallow' and 'disallowed' which would also need to be changed.

**Comment by elear** [comment]
Other cases of allowed and disallowed absolutely should be addressed.  In this case we're talking about the nature of the data link.  Why is that the concern beyond even the router, much less the AS or ISD?
