### ISSUE TITLE
Add discussion about MTU & fragmentation

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-dp_I-D#39]
> Feedback Harald Alvestrand
> The description of SCION refers to using UDP/IP as the internal substrate inside an AS, and as a framing protocol on inter-AS links. This means that the Internet MTU of 1500 bytes (1200 for IPv6) will be in effect.
Path hops take 12 bytes + a couple of “segment headers” of 16 bytes - which means that a 10-hop, 3-segment path will take 168 bytes for the routing information. This is enough to reduce the MTU significantly, and the MTU will be unpredictable and maybe variable, since the path for a given packet may change dynamically.
(The packet format, like UDP’s, permits 68K-byte packets. However, fragmentation is A Thing.)

Related issues: 
* CP draft: https://github.com/scionassociation/scion-cp_I-D/issues/57 
* Implementations: https://github.com/scionproto/scion/issues/2608 

Also: 
- [x] Add discussion about fragmentation
- [x] Adapt this text  in the Common Header  paragraph` The value of the traffic class bits in a received packet or fragment might differ from the value sent by the packet's source. `

**Comment by jiceatscion** [comment]
Here's what I think we could say:

Fragmentation:
* At the UDP/SCION layer: no fragmentation ever. Like IPV6.
* In the underlay network. SCION is agnostic to datagram fragmentation by the underlay UDP layer. The option to fragment datagrams on a particular inter-AS link. Is the joint decision (not recommended) of the administrators of the two ASes involved. The decision to fragment datagrams at intra-AS interfaces is the decision of that AS' administrator.

MTU:
* SCION assumes that the underlay network supports a minimum MTU of 1280, regardless of whether it is IPV6 or IPV4.
* The MTU of an entire path is defined as the MIN of the MTUs of the links traversed by that path. The control plane makes that number available as part of each segment's metadata.
* SCION assumes that the MTU of a path segment remains correct for the life time of that segment.
* The MTU of each link may be discovered or administratively configured (current practice is for it to be configured). It must be less than or equal to the MTU of the underlying link-layer in either direction.
* Intra-AS network MTUs are a result of the network configuration of each AS and therefore predictable.
* Inter-AS links MTU are normally under the joint control of the administrators of the two ASes involved and therefore equally predictable.
* Although that isn't a normal use case, SCION allows inter-AS links to be routed through multiple IP routers, not necessarily under the control of either AS' administrator. In that case, the link's MTU MUST be configured statically to a conservative value. 1280 is a safe value. The same approach applies to all cases where MTUs cannot be assumed to be stable.

**Comment by jiceatscion** [comment]
Let me know if the above proposal is reasonable enough to tentatively add it to the draft.

**Comment by nicorusti** [comment]
Looks good, thanks a lot for putting together a paragraph out of this! 
Just some minor comments: 
* SCION assumes that its ~layer 2~ --> underlay ?
* On the last point (multiple ASes between two SCION routers): I'd say this is a special case and I'd not cover it in the draft

**Comment by jiceatscion** [comment]
> Looks good, thanks a lot for putting together a paragraph out of this! Just some minor comments:
> 
>     * SCION assumes that its ~layer 2~ --> underlay ?

In another issue, we have agreed that using un-encapsulated L2 was a valid scenario. As a result, an inter-AS link doesn't necessarily use an underlay network. From the P-o-V of SCION that is L2 either way. I admit that I have always been unsure how to designate encapsulation and tunneling layers with respect to the upper and lower layers: whatever L3 runs on top of could be called L2, but whatever encapsulates an L2 could be called L3. If there's a solid convention about this, I'll respect it.

>     * On the last point (multiple ASes between two SCION routers): I'd say this is a special case and I'd not cover it in the draft

Not "multiple ASes"; "multiple IP routers". It is true that ASes are supposed to connect at exchanges, with no routing, but we also know it's not the only use case by far. (The drafts, in my opinion, are too far from saying that this is wrong. May be that's what we should change. OTOH, that would be lying on the current state of deployments)

**Comment by nicorusti** [comment]
Regarding L2, maybe we just say lower layer? I am reluctant to use L2, as peple might think this is the MAC layer (which is not in many cases). 

> Not "multiple ASes"; "multiple IP routers". I

You mentioned `multiple IP routers, not necessarily under the control of either AS' administrator`, reading this I understand this is running the SCION link across multiple ASes (e.g. over Internet). Maybe you can just remove this wording and then it becomes clearer that you are just referring to multiple IP hops. Or remove the special case overall, as this is anyways an exception that IMHO should be avoided

**Comment by jiceatscion** [comment]
Ok. Will rephrase as you suggested and make a PR.
