### ISSUE TITLE
Payload integrity discussion - add section in security considerations

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-dp_I-D#44]
#### Feedback
> Harald 23.07.2024 
> There’s a nice description in the doc on how a man-in-the-middle attack could work; without alternate comms paths between entities, there seems to be no way to protect against those. 
However, there’s no discussion on preserving the integrity of the payloads; perhaps intentionally, as the gateway process may have to mangle them (by checksum modification, if nothing else).

> Response
The reason why we did not include this is that there is a proposal for an experimental extension ([SPAO](https://docs.scion.org/en/latest/protocols/authenticator-option.html)) to authenticate addresses, provide integrity protection for payloads, and replay protection. This is still very experimental and it not used in the production network, so we felt it was best to leave this out. We could add some text to explain why this property is not provided.

**Comment by jiceatscion** [comment]
I would propose adding a sub-section of "On-Path attacks":

### Payload modification

It is possible for an on-path attacker to modify the payload of a packet. The application layers can easily defend against such an attack without any cooperation by the SCION network, for that reason Payload integrity is not in scope for this specification. Yet, a standard and trusted payload integrity protection mechanism integral to SCION could be desirable. There exists a proposal for an experimental extension to authenticate addresses, provide integrity protection for payloads, and replay protection: [SPAO](https://docs.scion.org/en/latest/protocols/authenticator-option.html) .  This is still very experimental and it not used in the production network.

**Comment by nicorusti** [comment]
Slight rewording: 

> An on-path attacker may modify the payload of a SCION packet. Existing higher-layer protocols can easily defend against such an attack without any cooperation by the SCION network. For that reason, payload integrity is not in scope for this specification. There exists a proposal for an experimental extension to authenticate addresses, provide integrity protection for payloads, and replay protection: [SPAO](https://docs.scion.org/en/latest/protocols/authenticator-option.html) . This is still very experimental and it not used in the production network.

**Comment by jiceatscion** [comment]
I adopted your wording with two modifications:
* "may modify" -> "can modify" (due to the loaded ietf meaning of "may"). 
* "There exists" -> "However, there exists".
