### ISSUE TITLE
General review - forward references 

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-dp_I-D#45]
Go through the draft again and make sure there are no other forward references

Twin issues:
- https://github.com/scionassociation/scion-cp_I-D/issues/58
- https://github.com/scionassociation/scion-cppki_I-D/issues/36

**Comment by nicorusti** [comment]
@knmeynell [here](https://drive.google.com/file/d/1hNtOtWpkwSnsre7nMYJgDPUHbuVQTasi/view?usp=drive_link) you can find my paper review of version -02

**Comment by knmeynell** [comment]
After a couple of passes, I didn't find a whole lot of forward references, but have removed or re-written where I did find the odd one. One reference to SPAO is still in 'Security Considerations' because it's probably relevant to the discussion and does reference the 'Complete Guide to SCION'.

**Comment by nicorusti** [comment]
@knmeynell SPAO has the SCION book as a reference, so I don't think it counts as a forward ref. I think we can resolve this
