### ISSUE TITLE
Clarify that document does not relate to previous IETF work

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-dp_I-D#48]
We should add somewhere a sentence mentioning that the protocol was developed outside IETF for a while (ETH Zurich, Anapaya Systems, etc.), and that these document are meant to document the existing deployment. 

- [ ] repeat for all three drafts

> On 7 Aug 2024, at 17:36, Independent Submissions Editor (Eliot Lear) <rfc-ise@rfc-editor.org> wrote:
'Mike McBride' [<mmcbride7@gmail.com>](mailto:mmcbride7@gmail.com) 
E. Does the document make clear upfront how the specification does or does not relate to past or current IETF activities?
 
> No. That would be helpful including, perhaps, why they are individual submissions. Since SR seems to be taking the world by storm, it would perhaps help to explain (even briefly) how scion takes intradomain SR to the next level of a secure interdomain solution. But that might be better for the panrg scion overview document and not one of these ise documents. The current documents focus on BGP limitations which is fair.
Good idea, we could add somewhere a sentence mentioning that the protocol was developed outside IETF for a while (ETH Zurich, Anapaya Systems, etc.), and that these document are meant to document the existing deployment.

**Comment by nicorusti** [comment]
@knmeynell maybe you could have a go at this?

**Comment by knmeynell** [comment]
Added reference in Introduction section.
