### ISSUE TITLE
FlowID / IPv6 Flow Label

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-dp_I-D#54]
IMHO use of the `FlowID` field is underspecified in the draft. This is all we say:
> - `FlowID`: This 20-bit field labels sequences of packets to be treated in the network as a single flow. Sources MUST set this field.
 
 Context: 
in https://github.com/scionproto/scion/issues/3714 @shitz says: 
> Note, the QoS and FlowID fields where moved to the first line of the common header. This is to be in line with the IPv6 header from which we borrow the specifications of these two fields.
 
 I have some questions: 
*  What value should the source use and why?
* Is this the same as IPv6 Flow Labels? If yes, shall we just use the same naming  (Flow ID --> Flow Label)?
*  Can we refer to the rules for IPv6 FLow Labels (e.g. [rfc2460](https://datatracker.ietf.org/doc/html/rfc2460) section 6 )?

@oncilla do you have some background on this?

**Comment by oncilla** [comment]
> What value should the source use and why?

A random value per flow of traffic that the source creates.

The exact mechanism to choose such a value is protocol dependent.
E.g., QUIC has some guidance: https://datatracker.ietf.org/doc/html/rfc9000#section-9.7

In general, I think we should define something similar to https://datatracker.ietf.org/doc/html/rfc6437
and the source should be compliant with it.

> Is this the same as IPv6 Flow Labels? If yes, shall we just use the same naming (Flow ID --> Flow Label)?

It is yes, and we can rename if that makes things easier, IMO.

> Can we refer to the rules for IPv6 FLow Labels (e.g. [rfc2460](https://datatracker.ietf.org/doc/html/rfc2460) section 6 )?

I would rather refer to https://datatracker.ietf.org/doc/html/rfc6437

**Comment by nicorusti** [comment]
Thanks a lot for the clarifications! So we can add a reference to [rfc6437](https://datatracker.ietf.org/doc/html/rfc6437), and in this case I'll also reuse the name "Flow Label", it will be clearer given the direct reference to the RFC.
