### ISSUE TITLE
Life of a packet: is L2 link possible?

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-dp_I-D#55]
In 3. Life of a SCION Data Packet we have a L2 link between R1, R2. Is this something that comes from the book or is this actually possible today? Can any of the implementations actually support this?

I feel there are some missing pieces: 
* We'd need an [Assigned Protocol Number](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml) that can be used by L2
* Is there any need for a L2 discovery mechanism?

@jiceatscion 

phrasing to be adjusted: 

```
*Note:* Although technically there is no need for a UDP/IP
      underlay if two routers are directly connected, the SCION
      implementation always uses a UDP/IP underlay in practice.  This is
      to enable a common interface for all routers.
  ```

**Comment by nicorusti** [comment]
@jiceatscion confirmed he has not heard of instances of this. I think we can remove L2 from the text.

**Comment by jiceatscion** [comment]
For good measure I forwarded that question to the community; just in case someone has been toying with that.

**Comment by jiceatscion** [comment]
> * Is there any need for a L2 discovery mechanism?

I suppose it is not needed. The inter-as links are manually configured anyway. So, we would use layer2 addresses directly in the config. I guess some discovery protocol would allow to use only the ISD/AS in the link configs, thus avoiding the reliance on a somewhat inconstant MAC address. Broadcasting *any* empty path packet (BFD packet, say) would probably do the trick. All-in-all it looks like an easy thing to try.

**Comment by jiceatscion** [comment]
So, I just heard from Jelte Van Bommel at netsec. They have done that, using MPLS as their L2. He said, ethernet would work all the same. So.... may be we need to say something about that in the drafts.

**Comment by nicorusti** [comment]
I agree, we should mention that the other side L2 address needs to be externally configured (as otherwise an existing L2 discovery mechanism such as ARP would need to be modified)
