### ISSUE TITLE
SCMP - Be careful about forward references

### ISSUE THREAD

**Issue by elear** [scionassociation/scion-dp_I-D#8]
>  SCION also includes its own protocol to communicate failures to endpoints,
   the SCION Control Message Protocol (SCMP).  This protocol will be
   described in a separate document, which will follow later.

Text like this doesn't stand on its own.

**Comment by elear** [comment]
If SCMP is not important to the work, you can still mention it informationally, but then you must properly reference it.

**Comment by nicorusti** [comment]
Hi @elear , we removed forward references to SCMP, [see change diff](https://author-tools.ietf.org/api/iddiff?url_1=https://scionassociation.github.io/scion-dp_I-D/draft-dekater-scion-dataplane.txt&url_2=https://scionassociation.github.io/scion-dp_I-D/no_scmp_spec/draft-dekater-scion-dataplane.txt).  We now mention SCMP at the end of the draft, and we use our developer documentation as a reference: https://docs.scion.org/en/latest/protocols/scmp.html 

Does that work? 

An alternative reference would be the SCION book  section 4.7.
